"""Agregar campo solucion a orden

Revision ID: 2ac4eb6de299
Revises: 09c138dd901a
Create Date: 2026-01-25 23:35:47.371449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ac4eb6de299'
down_revision = '09c138dd901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('persona_reporta',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('persona_reporta',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
