"""Agregar usuario a adjuntos

Revision ID: 434720c5fec9
Revises: e585ec73bd19
Create Date: 2026-01-18 18:05:20.304701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '434720c5fec9'
down_revision = 'e585ec73bd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjuntos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.alter_column('archivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('orden_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('persona_reporta',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('persona_reporta',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('numero',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('adjuntos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('orden_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('archivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
