"""corregir relaciones usuario en orden

Revision ID: b9e123cf6f2c
Revises: 434720c5fec9
Create Date: 2026-01-22 19:52:31.057182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e123cf6f2c'
down_revision = '434720c5fec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_edita_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_edita_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('usuario_edita_id')

    # ### end Alembic commands ###
