"""Agregar estado a orden

Revision ID: da87331aedf9
Revises: 2ac4eb6de299
Create Date: 2026-01-26 19:40:26.681054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da87331aedf9'
down_revision = '2ac4eb6de299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
