"""ultimo editor de orden

Revision ID: f7e3dbb672d7
Revises: b9e123cf6f2c
Create Date: 2026-01-23 18:41:09.736418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e3dbb672d7'
down_revision = 'b9e123cf6f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_editor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['ultimo_editor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ultimo_editor_id')

    # ### end Alembic commands ###
